### ISSUE TITLE
Resolver bugs da tela de cadastro

### ISSUE THREAD

**Issue by jesse1983** [Kerilet/simple-profile#1]
- Campos de nome, sobrenome e info são editáveis
- Colocar campos um ao lado do outro em formato de grid (estudar https://css-tricks.com/snippets/css/complete-guide-grid/)
- Falta o title nas páginas
- Estudar flexbox (https://origamid.com/projetos/flexbox-guia-completo/)

**Comment by Kerilet** [comment]
-Title adicionado

-Grid em andamento

**Comment by Kerilet** [comment]
-Campos de nome, sobrenome e info já são editáveis;

-Grid ainda em andamento

**Comment by Kerilet** [comment]
-Grid adicionada e ajustada conforme pedido;
